[package]
name = "db-proc"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "*"
quote = "*"
serde = { version = "*", features = [ "derive" ] }
syn = "*"
toml = "*"
