[Constant]
symbol = "cons"
[[Constant.determinant]]
name = "value"
sort = "i32"

[Phi]
symbol = "ϕ"
[[Phi.determinant]]
name = "data"
sort = "::util::union_find::ClassId"
variadic = true

[Parameter]
symbol = "param"
[[Parameter.determinant]]
name = "index"
sort = "u32"

[Add]
symbol = "+"
[[Add.determinant]]
name = "lhs"
sort = "::util::union_find::ClassId"
[[Add.determinant]]
name = "rhs"
sort = "::util::union_find::ClassId"

[Subtract]
symbol = "-"
[[Subtract.determinant]]
name = "lhs"
sort = "::util::union_find::ClassId"
[[Subtract.determinant]]
name = "rhs"
sort = "::util::union_find::ClassId"

[Multiply]
symbol = "*"
[[Multiply.determinant]]
name = "lhs"
sort = "::util::union_find::ClassId"
[[Multiply.determinant]]
name = "rhs"
sort = "::util::union_find::ClassId"

[Divide]
symbol = "/"
[[Divide.determinant]]
name = "lhs"
sort = "::util::union_find::ClassId"
[[Divide.determinant]]
name = "rhs"
sort = "::util::union_find::ClassId"

[Modulo]
symbol = "%"
[[Modulo.determinant]]
name = "lhs"
sort = "::util::union_find::ClassId"
[[Modulo.determinant]]
name = "rhs"
sort = "::util::union_find::ClassId"

[EqualsEquals]
symbol = "="
[[EqualsEquals.determinant]]
name = "lhs"
sort = "::util::union_find::ClassId"
[[EqualsEquals.determinant]]
name = "rhs"
sort = "::util::union_find::ClassId"

[NotEquals]
symbol = "≠"
[[NotEquals.determinant]]
name = "lhs"
sort = "::util::union_find::ClassId"
[[NotEquals.determinant]]
name = "rhs"
sort = "::util::union_find::ClassId"

[Less]
symbol = "<"
[[Less.determinant]]
name = "lhs"
sort = "::util::union_find::ClassId"
[[Less.determinant]]
name = "rhs"
sort = "::util::union_find::ClassId"

[LessEquals]
symbol = "≤"
[[LessEquals.determinant]]
name = "lhs"
sort = "::util::union_find::ClassId"
[[LessEquals.determinant]]
name = "rhs"
sort = "::util::union_find::ClassId"

[Greater]
symbol = ">"
[[Greater.determinant]]
name = "lhs"
sort = "::util::union_find::ClassId"
[[Greater.determinant]]
name = "rhs"
sort = "::util::union_find::ClassId"

[GreaterEquals]
symbol = "≥"
[[GreaterEquals.determinant]]
name = "lhs"
sort = "::util::union_find::ClassId"
[[GreaterEquals.determinant]]
name = "rhs"
sort = "::util::union_find::ClassId"
